language: cpp
services: docker
git:
  quiet: true
matrix:
  - ROS_DISTRO: melodic
  - ROS_DISTRO: kinetic

before_install:
  - docker build -f .devcontainer/Dockerfile -t ros-ci:${ROS_DISTRO} . --target ros-ci --build-args ROS_VERSION=${ROS_DISTRO}

script:
  - docker run --rm -i ros-ci:${ROS_DISTRO} "catkin build --this -DCMAKE_BUILD_TYPE=Release && catkin test --this"