language: cpp

services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  # not going to add code coverage, codacy, and run sanitizer as in github action cuz this is trashiv bruh
  matrix:
    - ROS_DISTRO="melodic"
    - ROS_DISTRO="kinetic"

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
