name: build-ros-docker
inputs:
  ros_distro:
    required: true
  compiler:
    required: true
  llvm_version:
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./.devcontainer/Dockerfile
        push: false
        build-args: |
          ROS_VERSION=${{ inputs.ros_distro }}
          USE_CLANG=${{ inputs.compiler == 'clang++' && 1 || '' }}
          LLVM_VERSION=${{ input.llvm_version }}
        tags: ros-ci:latest
        target: ros-ci
        load: true
