name: coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    env:
      cache_dir: ${{ github.workspace }}/.ccache
      coverage_host_dir: ${{ github.workspace }}/coverage
      coverage_report_dir: /home/catkin_ws/build/${{ github.event.repository.name }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ros_distro: [melodic]
        compiler: [g++]
    steps:
      - uses: actions/checkout@v3
      - run: mkdir ${{ env.coverage_host_dir }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.cache_dir }}
          key: ccache-${{ matrix.ros_distro }}
      - uses: ./.github/action/build_and_run_docker
        with:
          ros_distro: ${{ matrix.ros_distro }}
          compiler: ${{ matrix.compiler }}
          docker_run_opt: |
            -v ${{ env.coverage_host_dir }}:${{ env.coverage_report_dir }}
            -v ${{ github.workspace }}:/home/catkin_ws/src/${{ github.event.repository.name }}
          cmd: |
            . /opt/ros/${{ matrix.ros_distro }}/setup.bash
            cd /home/catkin_ws/src/${{ github.event.repository.name }}
            catkin build --this -v -DCMAKE_BUILD_TYPE=Coverage -DCOVERAGE_REPORT_NAME=coverage.xml
            catkin test --this -v
      - uses: codecov/codecov-action@v3
        with:
          flags: ${{ runner.os }}-${{ matrix.ros_distro }}
          name: ${{ matrix.ros_distro }}-coverage
          token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          files: ${{ env.coverage_host_dir }}/coverage.xml
          verbose: true
