name: sanitizer

on: [push, pull_request]

jobs:
  run-sanitizer:
    runs-on: ${{ matrix.os }}
    env:
      ccache_dir: ${{ github.workspace }}/.ccache
      docker_sanitizer_report_dir: /home/catkin_ws/src/${{ github.event.repository.name }}/sanitizer_report
      host_sanitizer_report_dir: ${{ github.workspace }}/shared
    strategy:
      matrix:
        os: [ubuntu-latest]
        ros_distro: [kinetic, melodic]
        sanitizer_options: [TSAN, ASAN, UBSAN]
        compiler: [g++, clang++]
        include:
          - sanitizer_options: TSAN
            sanitizer_flag: detect_deadlocks=0:suppressions=/home/catkin_ws/src/${{ github.event.repository.name }}/tool/sanitizer/tsan.supp:exitcode=0
          - sanitizer_options: ASAN
            sanitizer_flag: detect_invalid_pointer_pairs=1:detect_stack_use_after_return=1:check_initialization_order=1:halt_on_error=1
          - sanitizer_options: UBSAN
            sanitizer_flag: halt_on_error=1
          - compiler: clang++
            ros_distro: melodic
            llvm_version: 13
          - compiler: clang++
            ros_distro: kinetic
            llvm_version: 12
          - compiler: g++
            llvm_version: ""
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ env.ccache_dir }}
          key: ccache-${{ matrix.ros_distro }}-${{ matrix.sanitizer_options }}
      - run: mkdir ${{ env.host_sanitizer_report_dir }}
      - uses: ./.github/action/build_and_run_docker
        if: runner.os == 'Linux'
        with:
          ros_distro: ${{ matrix.ros_distro }}
          compiler: ${{ matrix.compiler }}
          llvm_version: ${{ matrix.llvm_version }}
          docker_run_opt: |
            -v ${{ env.host_sanitizer_report_dir }}:/shared
          cmd: |
            mkdir -p ${{ env.docker_sanitizer_report_dir }}
            catkin build --this -v -DENABLE_${{ matrix.sanitizer_options }}=ON -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=Debug
            ${{ matrix.sanitizer_options }}_OPTIONS=log_path=${{ env.docker_sanitizer_report_dir }}/${{ matrix.sanitizer_options }}-${{ matrix.ros_distro }}.log:${{ matrix.sanitizer_flag }} catkin test --this -v
            mv ${{ env.docker_sanitizer_report_dir }}/ /shared
      - run: sudo chmod -R a+r ${{ env.host_sanitizer_report_dir }}/sanitizer_report # kinda hack
      - uses: actions/upload-artifact@v3
        with:
          name: sanitizer-report
          path: ${{ env.host_sanitizer_report_dir }}
