name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      cache_dir: ${{ github.workspace }}/.ccache
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-latest]
        ros_distro: [noetic]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          path: src/${{ github.event.repository.name }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.cache_dir }}
          key: ccache-${{ matrix.ros_distro }}
      - name: Install
        shell: cmd
        run: |
          mkdir c:\opt\chocolatey
          set ChocolateyInstall=c:\opt\chocolatey
          choco upgrade git -y --no-progress
          choco sources add -n=ros-win -s https://aka.ms/ros/public --priority 1
          choco upgrade ros-%ROSDISTRO%-desktop_full -y --no-progress --execution-timeout=0
          choco install ninja -y --no-progress
          choco install ccache -y --no-progress
          choco upgrade cmake -y --no-progress --installargs 'ADD_CMAKE_TO_PATH=System'

          : The desktop_full deployment has a chocolatey deployment which is isolated to the ROS distro
          : (so they don't conflict with each other)
          : If you need other dependencies, they should go after setup.bat in the following block in order
          : to be injected into the isolated deployment.
        env:
          ROSDISTRO: ${{ matrix.ros_distro }}
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Build
        shell: cmd
        run: |
          call "C:\opt\ros\%ROSDISTRO%\x64\setup.bat"

          : Additional dependencies after setup.bat.
          : For other ROS repos, remove the : and add the clone commands
          pushd src
          git clone https://github.com/google/googletest
          popd

          : For other chocolatey packages, remove the : and add the choco packages

          : For vcpkgs, remove the : and add the vcpkg dependencies.
          : vcpkg install <package>

          catkin_make -DCMAKE_BUILD_TYPE=Debug -DWARNINGS_AS_ERRORS=OFF -DENABLE_ASAN=ON
        env:
          ROSDISTRO: ${{ matrix.ros_distro }}
      - name: Run Test
        shell: cmd
        run: |
          call "C:\opt\ros\%ROSDISTRO%\x64\setup.bat"
          call "${{ github.workspace }}\devel\setup.bat"

          catkin_make run_tests
        env:
          ROSDISTRO: ${{ matrix.ros_distro }}
